config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_user', to: 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
has_many :user_stocks
has_many :users, through: :user_stocks
validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
              publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
              endpoint: 'https://sandbox.iexapis.com/v1'
            )
    begin
      return new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name,
         last_price: client.price(ticker_symbol))
    rescue
      return nil
    end
  end
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def can_track_stock(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def can_add_friend(friend)
    !Friendship.where(user_id: self.id, friend_id: friend.id).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])
    if friend
      @user_stock = Friendship.new(user:current_user, friend: friend)
      if @user_stock.save
        flash[:notice] = "Friend #{friend.email} succesfully added to portfolio"
      end
    else
      flash[:notice] = "Usuario No Encontrado"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = Friendship.where(friend: params[:id], user: current_user).first
    friendship.destroy
    flash[:notice] = "Stock removed succesfully"
    redirect_to my_friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if !@stock
        flash.now[:alert] = "Please enter a proper symbol to search"
      end
    else
      flash.now[:alert] = "Please enter a symbol to search"
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker]) 
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.new(user:current_user, stock: stock)
    if @user_stock.save
      flash[:notice] = "Stock #{stock.name} succesfully added to portfolio"
    end
    redirect_to my_portfolio_path
  end

  def destroy
    userstock = UserStock.where(stock: params[:id], user: current_user).first
    userstock.destroy
    flash[:notice] = "Stock removed succesfully"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    if params[:email].present?
      @friend = User.where(email: params[:email]).first
      if !@friend
        flash.now[:alert] = "Please enter a proper symbol to search"
      end
    else
      flash.now[:alert] = "Please enter a email to search"
    end
    respond_to do |format|
      format.js { render partial: 'users/result_friendship' }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Finance Tracker', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if current_user %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if (request.path == my_portfolio_path) %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if (request.path == my_friends_path) %>">
            <%= link_to 'My Friends', my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-xs btn-danger logout-button" %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
  <% if alert || notice %>
    <% alert_type = notice ? 'success' : ( alert ? 'danger' : '' ) %>
    <div class="alert alert-<%= alert_type %>">

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= notice %> <%= alert %>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
 <div class="row col-md-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td>
            <%= link_to "Remove Stock", user_stock_path(stock.id), method: :delete, data: {confirm: "Are you Sure?"}, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>

app/views/stocks/_stock.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol:</strong> <%= @stock.ticker %>
    <strong>Name:</strong> <%= @stock.name %>
    <strong>Last Price:</strong> <%= @stock.last_price %>
  </div>
  <% if current_user.can_track_stock(@stock.ticker) %>
    <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), method: :post,class:'btn btn-info' %>
  <% elsif !under_stock_limit? %>
    <span class="badge badge-danger"> Max Reached </span>
  <% else %>
    <span class="badge badge-default"> Already Added </span>
  <% end %>
<% end %>

app/views/stocks/search.html.erb
<h1>Stock#search</h1>
<p>Find me in app/views/stock/search.html.erb</p>

app/views/users/_friend.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @friend %>
  <div class="card card-header results-block">
    <strong>Id:</strong> <%= @friend.id %>
    <strong>E-Mail:</strong> <%= @friend.email %>
  </div>
  <% if current_user.can_add_friend(@friend) %>
    <%= link_to "Add Friends", friendships_path(friend: @friend), method: :post, class:'btn btn-info' %>
  <% else %>
    <span class="badge badge-default"> Already Added </span>
  <% end %>
<% end %>

app/views/users/_friends_list.html.erb
 <div class="row col-md-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
        <tr>
          <th scope="row"><%= friend.email %></th>
          <td>
            <%= link_to "Remove friend", friendship_path(friend.id), method: :delete, data: {confirm: "Are you Sure?"}, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
        <% end %>
        </tr>
      </tbody>
    </table>
  </div>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'stocks/stock' %>"

app/views/users/_result_friendship.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'users/friend' %>"

app/views/users/my_friends.html.erb
<h1>My Friends</h1>
<div class="search-area">
  <h3>Search Users</h3>
  <%= form_tag search_user_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :email, params[:email], placeholder: "Enter user email",
                            autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-md-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon "search 2x" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results" class="mb-3"> 
</div>
<% if !@friends.empty? %>
 <%= render "users/friends_list" %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Enter Stock Symbol",
                            autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-md-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon "search 2x" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results" class="mb-3"> 
</div>
<% if !@tracked_stocks.empty? %>
 <%= render "stocks/list" %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome To Fincance tracker</h1>
<p>this app is for education purposes only </p>